service: ddarwin-aws-node-express-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
    layers:
      - arn:aws:lambda:sa-east-1:044815399860:layer:gremlin-lambda-x86_64:13
    environment:
      GREMLIN_TEAM_ID: 7d26e984-659b-5857-aabb-744f27915055
      GREMLIN_TEAM_CERTIFICATE_FILE: /var/task/cert.pem 
      GREMLIN_TEAM_PRIVATE_KEY_FILE: /var/task/key.pem
      GREMLIN_DEBUG: true
      GREMLIN_LAMBDA_ENABLED: true
      FAILURE_FLAGS_ENABLED: true
      GREMLIN_API_ENDPOINT_URL: https://beta.gremlin.com/v1
      # GREMLIN_CONFIG_FILE: /var/task/config.yaml