service: optum-demo-node-express-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'
    layers:
      - arn:aws:lambda:us-west-1:044815399860:layer:gremlin-lambda-arm64:13
    environment:
      GREMLIN_TEAM_ID: <gremlin_team_id>
      GREMLIN_TEAM_CERTIFICATE_FILE: /var/task/cert.pem 
      GREMLIN_TEAM_PRIVATE_KEY_FILE: /var/task/key.pem
      GREMLIN_DEBUG: true
      GREMLIN_LAMBDA_ENABLED: true
      FAILURE_FLAGS_ENABLED: true
      GREMLIN_API_ENDPOINT_URL: https://api.gremlin.com/v1
      # GREMLIN_CONFIG_FILE: /var/task/config.yaml
